import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeProvider } from "@/components/ThemeProvider";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = (await cookies()).get("theme")?.value ?? "dark";

  return (
    <html
      lang="es"
      className={theme === "dark" ? "dark" : ""}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <ThemeProvider initialTheme={theme}>{children}</ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
